# spring:
# datasource:
# url: jdbc:mysql://localhost:3306/inventory_db
# username: root
# password: root
# jpa:
# hibernate:
# ddl-auto: update
# show-sql: true


# Configure Database
# Create DB: inventory_db
# Update application.yml
# Run the application


# spring:
# datasource:
# url: jdbc:mysql://localhost:3306/inventory_db
# username: root
# password: root
# jpa:
# hibernate:
# ddl-auto: update
# show-sql: true